#server:
#  port: 8082
#
#spring:
#  profile:
#    active: qa
#
#---
#
#spring:
#  profile : qa
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    password: Suneel@89
#    url: jdbc:mysql://localhost:3306/dcbapp
#    username: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#welcome:
#  message: all the best suneel
#
#---
#
#spring:
#  profile : dev
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    password: Suneel@89
#    url: jdbc:mysql://localhost:3306/dcbapp-dev
#    username: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#welcome:
#  message: all the best suneel
#
#---
#
#spring:
#  profile : prod
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    password: Suneel@89
#    url: jdbc:mysql://localhost:3306/dcbapp-prod
#    username: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#welcome:
#  message: all the best suneel

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: env,beans
